// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzNd3ly0Sm5C2RnONu8Vv0y4gSIf2Ti7k',
    appId: '1:454318568826:web:51cd864af6fbfbf2c892c3',
    messagingSenderId: '454318568826',
    projectId: 'marketoz',
    authDomain: 'marketoz.firebaseapp.com',
    storageBucket: 'marketoz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9Meqf-9L1ag3mxRHuTTdrjyeAcDUKj8',
    appId: '1:454318568826:android:45f9d0b781aedafbc892c3',
    messagingSenderId: '454318568826',
    projectId: 'marketoz',
    storageBucket: 'marketoz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbGPWPoSWS4-x_WimP09VXvurB32l_rNE',
    appId: '1:454318568826:ios:ac0a1105a56113adc892c3',
    messagingSenderId: '454318568826',
    projectId: 'marketoz',
    storageBucket: 'marketoz.appspot.com',
    iosBundleId: 'com.example.marketos',
  );

}